version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-first-java-app-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kx025zzugrzu"
s3_prefix = "aws-sam-first-java-app-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
